server {
    listen 8000 ssl;
    listen [::]:8000 ssl;

    server_name _;

    # === Прямое указание путей к EC-сертификатам ===
    ssl_certificate /etc/nginx/certs/storage-api/cert.crt;
    ssl_certificate_key /etc/nginx/certs/storage-api/private.key;

    # === Параметры SSL (прописаны напрямую) ===
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256;
    ssl_ecdh_curve prime256v1:secp384r1;
    ssl_session_timeout 10m;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    location / {
        proxy_pass http://127.0.0.1:8001;
    }

    location ~ ^/collections/[0-9]+/upload {
        proxy_pass http://localhost:8001;

        client_max_body_size 1024G;
        client_body_timeout 7200s;
        proxy_request_buffering off;
    }
}